global:
  qsname: quickstart-microsoft-rdgateway
  owner: quickstart-eng@amazon.com
  marketplace-ami: false
  reporting: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  quickstart-microsoft-rdgatewayt1:
    template_file: quickstart-microsoft-rdgateway-example1.template
    parameter_input: quickstart-microsoft-rdgateway-exampleparms1.json
  quickstart-microsoft-rdgatewayt2:
    template_file: quickstart-microsoft-rdgateway-example2.template
    parameter_input: quickstart-microsoft-rdgateway-exampleparms2.json
